<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span><ul class="toc-item"><li><span><a href="#Numpy简介" data-toc-modified-id="Numpy简介-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Numpy简介</a></span></li><li><span><a href="#ndarray" data-toc-modified-id="ndarray-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>ndarray</a></span></li></ul></li><li><span><a href="#ndarray数组的创建和变换" data-toc-modified-id="ndarray数组的创建和变换-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>ndarray数组的创建和变换</a></span><ul class="toc-item"><li><span><a href="#从Python中的列表、元组等类型创建ndarray数组。" data-toc-modified-id="从Python中的列表、元组等类型创建ndarray数组。-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>从Python中的列表、元组等类型创建ndarray数组。</a></span></li><li><span><a href="#使用-NumPy中函数创建ndarray数组,如:-arange,-ones,-zeros等" data-toc-modified-id="使用-NumPy中函数创建ndarray数组,如:-arange,-ones,-zeros等-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>使用 NumPy中函数创建ndarray数组,如: arange, ones, zeros等</a></span></li><li><span><a href="#ndarray数组的变换" data-toc-modified-id="ndarray数组的变换-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>ndarray数组的变换</a></span><ul class="toc-item"><li><span><a href="#ndarray数组的维度变换" data-toc-modified-id="ndarray数组的维度变换-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>ndarray数组的维度变换</a></span></li><li><span><a href="#ndarray数组的类型变换" data-toc-modified-id="ndarray数组的类型变换-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>ndarray数组的类型变换</a></span></li></ul></li></ul></li><li><span><a href="#ndarray数组的操作" data-toc-modified-id="ndarray数组的操作-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>ndarray数组的操作</a></span><ul class="toc-item"><li><span><a href="#数组的索引和切片" data-toc-modified-id="数组的索引和切片-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>数组的索引和切片</a></span></li><li><span><a href="#ndarray数组的运算" data-toc-modified-id="ndarray数组的运算-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>ndarray数组的运算</a></span></li></ul></li><li><span><a href="#NumPy的随机数函数" data-toc-modified-id="NumPy的随机数函数-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>NumPy的随机数函数</a></span><ul class="toc-item"><li><span><a href="#NumPy的统计函数" data-toc-modified-id="NumPy的统计函数-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>NumPy的统计函数</a></span></li><li><span><a href="#NumPy的梯度函数" data-toc-modified-id="NumPy的梯度函数-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>NumPy的梯度函数</a></span></li></ul></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Exercise</a></span><ul class="toc-item"><li><span><a href="#Exercise-1:-Normalize-a-matrix" data-toc-modified-id="Exercise-1:-Normalize-a-matrix-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Exercise 1: Normalize a matrix</a></span></li><li><span><a href="#Exercise-2:-Learn-by-reading-document" data-toc-modified-id="Exercise-2:-Learn-by-reading-document-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Exercise 2: Learn by reading document</a></span></li><li><span><a href="#Exercise-3:-Clip" data-toc-modified-id="Exercise-3:-Clip-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Exercise 3: Clip</a></span></li></ul></li></ul></div>

## Numpy

### Numpy简介

- NumPy是一个开源的Python科学计算机出库
- 一个强大的N维数组对象 ndarray
- 广播功能函数
- 整合C/C++/Fortran代码得工具
- 线性代数，傅里叶变化，随机数生成

### ndarray

- 传统计算，比较麻烦。关注点在一个一个元素上

- 数组对象可以去掉元素间运算所需的循环，是一维向量更像单个数据

- 设置专门的数组对象，经过优化，可以提升这类应用的运算速度

- 科学计算中，一般一个维度所有的数据的类型`往往相同`

- 数组对象采用相同的数据类型，有利于节省运算和存储空间

- 由两部分构成
    - 实际的数据
    - 描述这些数据的元数据（数据维度，数据类型等）

- ndarray数组一般要求所有元素类型相同，数据下标从0开始

- ndarray在程序中的别名是：array

- np.array()输出成[]形式，元素由空格分裂

- 轴（axis）：保存数据的维度
    - 矩阵（二维数组）
        - 第一轴`(axis=0)`是矩阵的列操作
        - 第二轴`(axis=1)`是矩阵的行操作
     - 三维数组
        - 第三轴`(axis=2)`为图像矩阵的通道

- 秩（rank）：轴的数量

- ndarray对象的属性
<img src="numpy.assets/image-20200430152909151.png" alt="image-20200430152909151" style="zoom:50%;" />
- ndarray的元素类型
<img src="numpy.assets/image-20200430153159484.png" alt="image-20200430153159484" style="zoom:50%;" />
> intc与计算机有关

<img src="numpy.assets/image-20200430153415592.png" alt="image-20200430153415592" style="zoom:50%;" />

<img src="numpy.assets/image-20200430153432802.png" alt="image-20200430153432802" style="zoom:50%;" />

> 实部(.real)+ j虚部(.imag)

> 科学计算涉及数据较多,对存储和性能都有较高要求。
>
> 对元素类型精细定义,有助于 NumPy合理使用存储空间并优化性能。
>
> 对元素类型精细定义,有助于程序员对程序规模有合理评估。

- ndarray数组可以由非同质对象构成
    - 非同质ndarray元素为对象类型
    - 非同质ndarray对象无法有效发挥NumPy优势，尽量避免使用

## ndarray数组的创建和变换

### 从Python中的列表、元组等类型创建ndarray数组。

   > 当不指定dtype时，NumPy将根据数据情况关联一个dtype类型
   >
   > 元组和列表混合类型创建

 

In [10]:
import numpy as np
li = [1, 2, 3, 4]
x = np.array(li)
print(x)
x = np.array(li, dtype=np.float32)
print(x)

[1 2 3 4]
[1. 2. 3. 4.]


### 使用 NumPy中函数创建ndarray数组,如: arange, ones, zeros等

 - 最常用的函数

   <img src="numpy.assets/image-20200430154644719.png" alt="image-20200430154644719" style="zoom:50%;" />

   <img src="numpy.assets/image-20200430155034435.png" alt="image-20200430155034435" style="zoom:50%;" />

   <img src="numpy.assets/image-20200430155139710.png" alt="image-20200430155139710" style="zoom:50%;" />
   
  > 除了arrage其余生成都是浮点数类型

In [18]:
print(np.zeros((2, 3)))
print(np.zeros((2, 3), dtype=int))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


In [28]:
np.linspace(start=10, stop=20, num=10, endpoint=True, retstep=False, dtype=int, axis=-1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

> start: 返回样本数据开始点
>
> stop:返回样本数据结束点
>
> num:生成的样本数据量，默认为50
>
> endpoint：True则包含stop；False则不包含stop
>
> retstep：If True, return (samples, step), where step is the spacing between samples.(即如果为True则结果会给出数据间隔)
>
> dtype：输出数组类型
>
> axis：0(默认)或-1

> linspace生成的默认为浮点数
>
> 科学计算中一般都是浮点数

In [32]:
x = np.ones((2, 3), dtype=int)
y = np.zeros((2, 3), dtype=int)
print(np.concatenate((x, y), axis=0))
print(np.concatenate((x, y), axis=1))

[[1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]]
[[1 1 1 0 0 0]
 [1 1 1 0 0 0]]


### ndarray数组的变换

#### ndarray数组的维度变换

   - ndarray数组的维度变换方法

     <img src="numpy.assets/image-20200430155951356.png" alt="image-20200430155951356" style="zoom:50%;" />

     > resize和reshape功能一致
     >
     > resize返回的是之前的数组，形成一个新的数组
     >
     > reshape不改变原数组，包含原数组的备份

     

In [50]:
y = np.arange(1, 100, 3)
print(y)
y = y.reshape((3, -1))
print(y)
y = y.reshape((-1, 3))
print(y)
y = y.swapaxes(0, 1)
print(y)
y = y.flatten()
print(y)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
[[ 1  4  7 10 13 16 19 22 25 28 31]
 [34 37 40 43 46 49 52 55 58 61 64]
 [67 70 73 76 79 82 85 88 91 94 97]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]
 [28 31 34]
 [37 40 43]
 [46 49 52]
 [55 58 61]
 [64 67 70]
 [73 76 79]
 [82 85 88]
 [91 94 97]]
[[ 1 10 19 28 37 46 55 64 73 82 91]
 [ 4 13 22 31 40 49 58 67 76 85 94]
 [ 7 16 25 34 43 52 61 70 79 88 97]]
[ 1 10 19 28 37 46 55 64 73 82 91  4 13 22 31 40 49 58 67 76 85 94  7 16
 25 34 43 52 61 70 79 88 97]


- mat (or array).reshape(c, -1) 必须是矩阵格式或者数组格式，才能使用 .reshape(c, -1) 函数， 表示将此矩阵或者数组重组，以 c行d列的形式表示
- reshape(m,-1) #改变维度为每一列m行
- reshape(-1,m) #改变维度为每一行m列
- -1的作用: 自动计算d：d=数组或者矩阵里面所有的元素个数/c, d必须是整数，不然报错）

#### ndarray数组的类型变换

In [47]:
x = y.astype(float)
print(x)

[ 1. 10. 19. 28. 37. 46. 55. 64. 73. 82. 91.  4. 13. 22. 31. 40. 49. 58.
 67. 76. 85. 94.  7. 16. 25. 34. 43. 52. 61. 70. 79. 88. 97.]


 > astype()是一定会创建一个新的数组（原始数据的一个拷贝）

- ndarray向list转换

In [49]:
ls = x.tolist()
print(ls)

[1.0, 10.0, 19.0, 28.0, 37.0, 46.0, 55.0, 64.0, 73.0, 82.0, 91.0, 4.0, 13.0, 22.0, 31.0, 40.0, 49.0, 58.0, 67.0, 76.0, 85.0, 94.0, 7.0, 16.0, 25.0, 34.0, 43.0, 52.0, 61.0, 70.0, 79.0, 88.0, 97.0]


 > list的速度可能会比numpy慢

## ndarray数组的操作

### 数组的索引和切片

- 索引:获取数组中特定位置元素的过程
- 切片:获取数组元素子集的过程

- 一维数组的索引和切片

   - 与python类似


- 多维数组的索引

   - 索引：在每个维度指定序号

In [53]:
a = np.arange(24).reshape((2, 3, 4))
print(a)
print(a[1, 2, 3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
23


   - 切片

In [56]:
print(a[:, 1, -3])
print(a[:, 1, ::2])
print(a[:, :, ::2])

[ 5 17]
[[ 4  6]
 [16 18]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


- 索引一维数组

In [80]:
x = np.arange(10,1,-1)
print(x)
print(x[np.array([3, 3, 1, 8])])

[10  9  8  7  6  5  4  3  2]
[7 7 9 2]


> 索引数组必须为整数类型。数组中的每个值指示数组中要使用哪个值来代替索引。

In [83]:
print(x[np.array([[1,1],[2,3]])])

[[9 9]
 [8 7]]


> 一般来说，使用索引数组时返回的数组是与索引数组形状相同的数组，但数组的类型和值正在编制索引。

- 索引多维数组

In [82]:
y=np.arange(35).reshape(5,7)
print(y)
print(y[np.array([0,2,4]),np.array([0,1,2])]  )  #等价于y[[0,2,4],[0,1,2]]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[ 0 15 30]


> 在这种情况下，如果索引数组具有匹配的形状，并且要编制索引的数组的每个维度都有一个索引数组，则结果数组的形状与索引数组相同，并且这些值对应于索引数组中每个位置的索引集。在此示例中，两个索引数组的第一个索引值为 0，因此结果数组的第一个值是 y[0，0]。下一个值是 y[2，1]，最后一个值是 y[4，2]。

In [78]:
y[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

> 如果索引数组没有相同的形状，则尝试将它们广播到相同的形状。如果无法广播到相同形状，则引发异常

In [84]:
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

> 广播机制允许索引数组与其他索引的标量组合。其效果是，标量值用于索引数组的所有相应值

In [86]:
 y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

> 结果是构建一个新数组，其中索引数组的每个值从被索引的数组中选择一行，生成的数组具有生成的形状(索引元素的数量、行大小)。

- Boolean or “mask” index arrays

In [87]:
b = y > 20
print(b)
print(y[b])

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34]


> 整数索引数组不同，在布尔的情况下，结果是一个一维数组，其中包含索引数组中对应于布尔数组中所有真实元素的所有元素。

In [89]:
print(b[:, 5])
print(y[b[:, 5]])

[False False False  True  True]
[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


> In general, when the boolean array has fewer dimensions than the array being indexed, this is equivalent to y[b, ...], which means y is indexed by b followed by as many : as are needed to fill out the rank of y. Thus the shape of the result is one dimension containing the number of True elements of the boolean array, followed by the remaining dimensions of the array being indexed.

In [93]:
x = np.arange(30).reshape(2, 3, 5)
print(x)
print('-'*50)
b = np.array([[True, True, False], [False, True, True]])
print(x[b])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
--------------------------------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### ndarray数组的运算

1. 数组与标量之间的运算

   - 作用于数组的每一个元素 

     > a.mean() 求一个数组的平均值

   - NumPy一元函数

     <img src="numpy.assets/image-20200430171431472.png" alt="image-20200430171431472" style="zoom:50%;" />

     > ceil 不超过这个元素的整数值
     >
     > floor 小于这个元素的最大整数值

     <img src="numpy.assets/image-20200430171525549.png" alt="image-20200430171525549" style="zoom:50%;" />

2. 二元函数

   - 二元函数

     <img src="numpy.assets/image-20200430174249808.png" alt="image-20200430174249808" style="zoom:50%;" />

In [64]:
x = np.arange(10)
y = np.arange(10, 20)
print(x, y, x + y, sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]


In [59]:
# Apply a function to a matrix

# power of 2
print(np.power(x, 2))

[ 0  1  4  9 16 25 36 49 64 81]


In [60]:
# sin
print(np.sin(x))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [65]:
# square root
print(np.sqrt(x))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [66]:
x = np.arange(15, dtype=float)
x = x.reshape((3, -1))
x[:2, 1:3] *= -1
x

array([[ 0., -1., -2.,  3.,  4.],
       [ 5., -6., -7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [69]:
# Check element-wise
print(x > 0)

[[False False False  True  True]
 [ True False False  True  True]
 [ True  True  True  True  True]]


## NumPy的随机数函数

1. np.random的随机数函数

   - <img src="numpy.assets/image-20200430202104425.png" alt="image-20200430202104425" style="zoom:50%;" />

     > seed()设定为一个值之后，使用上面的函数再次产生纬度和类型的随机数，结果是相同的
     >
     > seed()只能是一次有效

   - <img src="numpy.assets/image-20200430202516240.png" alt="image-20200430202516240" style="zoom:50%;" />

     > p可以是一个数组

   - <img src="numpy.assets/image-20200430211803282.png" alt="image-20200430211803282" style="zoom:50%;" />

### NumPy的统计函数

1. np常用的统计函数

   - <img src="numpy.assets/image-20200430213121808.png" alt="image-20200430213121808" style="zoom:50%;" />

     > 可以指定对某个轴进行统计运算
     >
     > 数组最外层，轴为0

In [98]:
a = np.arange(15).reshape(3, 5)
print(a)
print('-'*50)
print(np.mean(a, axis=0))
print('-'*50)
print(np.mean(a, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------------------------------------
[5. 6. 7. 8. 9.]
--------------------------------------------------
[ 2.  7. 12.]


<img src="numpy.assets/image-20200501080238090.png" alt="image-20200501080238090" style="zoom:50%;" />

In [99]:
print(np.argmax(a))
print(np.unravel_index(np.argmax(a), a.shape))

14
(2, 4)


### NumPy的梯度函数

1. 梯度

   - 连虚值之间的变化率，即斜率
    > 计算数组f中元素的梯度，当f为多维时，返回每个维度梯度
    >
    > XY坐标轴连续三个X坐标对应的Y轴值：a, b, c, 其中，b的梯度是：(c - a)/2，a的梯度是：(b - a)/1，c的梯度是：(b - c)/2

In [101]:
a = np.random.randint(0, 20, 5)
print(a)
print('-'*50)
print(np.gradient(a))

[ 4 18  3 15  7]
--------------------------------------------------
[14.  -0.5 -1.5  2.  -8. ]


In [110]:
import pprint
c = np.random.randint(0, 50, (3, 5))
print(c)
print('-'*50)
d = np.gradient(c)
pprint.pprint(d)

[[12 32 34 18 23]
 [46  9 48 32  2]
 [24 13 30 25 47]]
--------------------------------------------------
[array([[ 34. , -23. ,  14. ,  14. , -21. ],
       [  6. ,  -9.5,  -2. ,   3.5,  12. ],
       [-22. ,   4. , -18. ,  -7. ,  45. ]]),
 array([[ 20. ,  11. ,  -7. ,  -5.5,   5. ],
       [-37. ,   1. ,  11.5, -23. , -30. ],
       [-11. ,   3. ,   6. ,   8.5,  22. ]])]


<img src="numpy.assets/image-20200501081800886.png" alt="image-20200501081800886" style="zoom:50%;" />

## Exercise

### Exercise 1: Normalize a matrix

Given matrix `x`:

```python
x = np.random.uniform(10, size=(10, 5))
```

Normalize it using the formula:

$(x - x\_min) / (x\_max - x\_min)$

Try to use the function `np.max` and `np.min`.

### Exercise 2: Learn by reading document

For the same matrix `x`:

Find the mean value for every column and min value for every row.

Hint: you need to use parameter axis.

Reference: 
- https://numpy.org/doc/stable/reference/generated/numpy.amin.html#numpy.amin
- https://numpy.org/doc/stable/reference/generated/numpy.mean.html#numpy.mean

### Exercise 3: Clip

Implement a function `clip(matrix, low, high)`, return a matrix such that:

for every element e, if `e < low`, set `e = low`; if `e > high`, set `e = high`.

You should make a copy using `.copy()` and return a new matrix.